### ISSUE TITLE
Invalid ccli versoin returned 0.0.1

### ISSUE THREAD

**Issue by amokasha** [cloudblue/connect-cli#14]
When I try to check the **ccli** version, I always get **0.0.1**. I tested this on the latest 21.10 version. See the example below:
```
PS C:\Connect_CLI\connect-cli_21.10_windows_amd64\dist> .\ccli.exe --version

ccli, version 0.0.1
```

This should match the release version, in this case, 21.10

**Comment by marcserrat** [comment]
Thanks @amokasha, i take a look

**Comment by marcserrat** [comment]
Issue caused by new build procedure based on github actions. We will resolve on release 22
