### ISSUE TITLE
Error when running the template project, invalid statuses for usage_file_request_processing

### ISSUE THREAD

**Issue by rhudz-ingram** [cloudblue/connect-cli#184]
When a template extension project is created of type Fulfillment Automation and it's executed with `cextrun`,
the error is shown: `The status/es processed are invalid for the event usage_file_request_processing.`.

I determined it is due to the `processed` status included in the `statuses` argument for the method `handle_usage_file_request_processing`.

As I saw the template in this repository, the `processed` status is not included in the `USAGE_FILE_STATUSES` constant.  
And also the default Multi account extension project doesn't have this problem.

But in the Fulfillment type it keeps adding that status.

**Comment by marcserrat** [comment]
hi Rhudz,

this is old bug and corrected on new versions already of the system. Please ensure that you are using new version of the CLI tool and be careful with fact that CLI version 26 still is not supported in Connect Production

**Comment by marcserrat** [comment]
Hi rhudz,

specification has changed a bit in v26 and events are obtained dynamically from Connect platform. I reloaded the definitions in order to ensure that in environment you work has latest definitions.
